[tool.ruff.lint]
ignore = []
select = ["ALL"]

[tool.ruff]
fix = true
indent-width = 2
line-length = 88
required-version = ">=0.11.6"
show-fixes = true

[tool.ruff.format]
indent-style = "space"
line-ending = "lf"
quote-style = "double"
skip-magic-trailing-comma = false
